name: CI
env: # Set the secret as an input
  docker_username: strikzie
  docker_password: ${{ secrets.GITHUB_TOKEN }} #Nees to be set to be made available to the workflow
  GIT_COMMIT: ${{ github.sha }}
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  goofing: 
    name: goofing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: one-line script
        run: echo Hello NEW YORK CITY

      - name: multi-line script
        run: |
          echo May thy knife chip and shatter
          echo lisan al ghaib
  build-test-upload:
    name: build-test-upload
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v5       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  build-docker:
    name: build-docker
    runs-on: ubuntu-latest
    needs: [build-test-upload]
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: ls
        run: ls -la ci
      - name: build docker image
        run: bash ci/build-docker.sh
      - name: push docker image
        run: bash ci/push-docker.sh
        
    
